### ISSUE TITLE
Make seperate Contributor.md File

### ISSUE THREAD

**Issue by shivam7374** [shivam7374/Algorithm-Visualizer#12]
Make a separate Contributor.MD File

**Comment by shivam7374** [comment]
Also, remove the contributors section from the readme.

**Comment by ShrinathPawar** [comment]
If you don't mind, will you assign this issue to me?

**Comment by ShrinathPawar** [comment]
@shivam7374 please have a look at _**[this] (https://github.com/ShrinathPawar/Algorithm-Visualizer/tree/Adding-Contributor.md)**_!
