### ISSUE TITLE
Disable all sorting algorithms button once some algorithm is selected.

### ISSUE THREAD

**Issue by shivam7374** [shivam7374/Algorithm-Visualizer#22]
Disable all sort algorithms button once some algorithm is selected.

**Comment by WaniAthar** [comment]
@shivam7374 assign it to me.

**Comment by WaniAthar** [comment]
@shivam7374 check once, i have created a PR

**Comment by shivam7374** [comment]
@WaniAthar also disable the generate array buttons when the sorting has started.

**Comment by WaniAthar** [comment]
ok

**Comment by WaniAthar** [comment]
@shivam7374 please check once, i have disabled for generate buttons also
