### ISSUE TITLE
Add reset button 

### ISSUE THREAD

**Issue by shivam7374** [shivam7374/Algorithm-Visualizer#24]
Add a reset button to reset the initial state of the array before it started sorting the elements and enable this button only when the sorting has finished.

**Comment by smitioswal** [comment]
Please assign this to me

**Comment by SurajKD** [comment]
assign this to me

**Comment by SurajKD** [comment]
fixed please merge https://github.com/shivam7374/Algorithm-Visualizer/pull/27

**Comment by SurajKD** [comment]
fixed the issue please run and check
