### ISSUE TITLE
Allow User to input the array size

### ISSUE THREAD

**Issue by shivam7374** [shivam7374/Algorithm-Visualizer#6]
Allow the user to define the array size which would then be randomly generated and visualisation would be done on that array.

**Comment by subashpaul** [comment]
can i work on this?

**Comment by umairayub79** [comment]
Done, sent a PR
https://github.com/shivam7374/Algorithm-Visualizer/pull/8

**Comment by subashpaul** [comment]
Can i get a bit more details about the issue?
